<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-18 12:40

from django.db import migrations, models
import django.utils.timezone
=======
# Generated by Django 4.2.7 on 2023-11-18 11:23

from django.db import migrations, models
>>>>>>> origin/ClassBasedViews


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
<<<<<<< HEAD
            field=models.DateTimeField(default=django.utils.timezone.now),
=======
            field=models.DateTimeField(auto_now=True),
>>>>>>> origin/ClassBasedViews
        ),
    ]
