# Generated by Django 4.2.7 on 2023-11-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
